import { Metadata } from 'next'
import './styles/globals.scss'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Зеленный Мастер',
  description: 'Generated by create next app',
  icons: {
    icon: '/main-icon.svg',
    shortcut: '/main-icon.svg',
    apple: '/main-icon.svg',
  },
}

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
